// ==============================================================
// Generated by Vitis HLS v2023.2.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="main_func_main_func,hls_ip_2023_2_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9cg-ffvb1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=87,HLS_SYN_TPT=none,HLS_SYN_MEM=30,HLS_SYN_DSP=0,HLS_SYN_FF=2223,HLS_SYN_LUT=2570,HLS_VERSION=2023_2_1}" *)

module main_func (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_mem_AWVALID,
        m_axi_mem_AWREADY,
        m_axi_mem_AWADDR,
        m_axi_mem_AWID,
        m_axi_mem_AWLEN,
        m_axi_mem_AWSIZE,
        m_axi_mem_AWBURST,
        m_axi_mem_AWLOCK,
        m_axi_mem_AWCACHE,
        m_axi_mem_AWPROT,
        m_axi_mem_AWQOS,
        m_axi_mem_AWREGION,
        m_axi_mem_AWUSER,
        m_axi_mem_WVALID,
        m_axi_mem_WREADY,
        m_axi_mem_WDATA,
        m_axi_mem_WSTRB,
        m_axi_mem_WLAST,
        m_axi_mem_WID,
        m_axi_mem_WUSER,
        m_axi_mem_ARVALID,
        m_axi_mem_ARREADY,
        m_axi_mem_ARADDR,
        m_axi_mem_ARID,
        m_axi_mem_ARLEN,
        m_axi_mem_ARSIZE,
        m_axi_mem_ARBURST,
        m_axi_mem_ARLOCK,
        m_axi_mem_ARCACHE,
        m_axi_mem_ARPROT,
        m_axi_mem_ARQOS,
        m_axi_mem_ARREGION,
        m_axi_mem_ARUSER,
        m_axi_mem_RVALID,
        m_axi_mem_RREADY,
        m_axi_mem_RDATA,
        m_axi_mem_RLAST,
        m_axi_mem_RID,
        m_axi_mem_RUSER,
        m_axi_mem_RRESP,
        m_axi_mem_BVALID,
        m_axi_mem_BREADY,
        m_axi_mem_BRESP,
        m_axi_mem_BID,
        m_axi_mem_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 20'd1;
parameter    ap_ST_fsm_state2 = 20'd2;
parameter    ap_ST_fsm_state3 = 20'd4;
parameter    ap_ST_fsm_state4 = 20'd8;
parameter    ap_ST_fsm_state5 = 20'd16;
parameter    ap_ST_fsm_state6 = 20'd32;
parameter    ap_ST_fsm_state7 = 20'd64;
parameter    ap_ST_fsm_state8 = 20'd128;
parameter    ap_ST_fsm_state9 = 20'd256;
parameter    ap_ST_fsm_state10 = 20'd512;
parameter    ap_ST_fsm_state11 = 20'd1024;
parameter    ap_ST_fsm_state12 = 20'd2048;
parameter    ap_ST_fsm_state13 = 20'd4096;
parameter    ap_ST_fsm_state14 = 20'd8192;
parameter    ap_ST_fsm_state15 = 20'd16384;
parameter    ap_ST_fsm_state16 = 20'd32768;
parameter    ap_ST_fsm_state17 = 20'd65536;
parameter    ap_ST_fsm_state18 = 20'd131072;
parameter    ap_ST_fsm_state19 = 20'd262144;
parameter    ap_ST_fsm_state20 = 20'd524288;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_MEM_ID_WIDTH = 1;
parameter    C_M_AXI_MEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_MEM_DATA_WIDTH = 256;
parameter    C_M_AXI_MEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_USER_VALUE = 0;
parameter    C_M_AXI_MEM_PROT_VALUE = 0;
parameter    C_M_AXI_MEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_MEM_WSTRB_WIDTH = (256 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_mem_AWVALID;
input   m_axi_mem_AWREADY;
output  [C_M_AXI_MEM_ADDR_WIDTH - 1:0] m_axi_mem_AWADDR;
output  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_AWID;
output  [7:0] m_axi_mem_AWLEN;
output  [2:0] m_axi_mem_AWSIZE;
output  [1:0] m_axi_mem_AWBURST;
output  [1:0] m_axi_mem_AWLOCK;
output  [3:0] m_axi_mem_AWCACHE;
output  [2:0] m_axi_mem_AWPROT;
output  [3:0] m_axi_mem_AWQOS;
output  [3:0] m_axi_mem_AWREGION;
output  [C_M_AXI_MEM_AWUSER_WIDTH - 1:0] m_axi_mem_AWUSER;
output   m_axi_mem_WVALID;
input   m_axi_mem_WREADY;
output  [C_M_AXI_MEM_DATA_WIDTH - 1:0] m_axi_mem_WDATA;
output  [C_M_AXI_MEM_WSTRB_WIDTH - 1:0] m_axi_mem_WSTRB;
output   m_axi_mem_WLAST;
output  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_WID;
output  [C_M_AXI_MEM_WUSER_WIDTH - 1:0] m_axi_mem_WUSER;
output   m_axi_mem_ARVALID;
input   m_axi_mem_ARREADY;
output  [C_M_AXI_MEM_ADDR_WIDTH - 1:0] m_axi_mem_ARADDR;
output  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_ARID;
output  [7:0] m_axi_mem_ARLEN;
output  [2:0] m_axi_mem_ARSIZE;
output  [1:0] m_axi_mem_ARBURST;
output  [1:0] m_axi_mem_ARLOCK;
output  [3:0] m_axi_mem_ARCACHE;
output  [2:0] m_axi_mem_ARPROT;
output  [3:0] m_axi_mem_ARQOS;
output  [3:0] m_axi_mem_ARREGION;
output  [C_M_AXI_MEM_ARUSER_WIDTH - 1:0] m_axi_mem_ARUSER;
input   m_axi_mem_RVALID;
output   m_axi_mem_RREADY;
input  [C_M_AXI_MEM_DATA_WIDTH - 1:0] m_axi_mem_RDATA;
input   m_axi_mem_RLAST;
input  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_RID;
input  [C_M_AXI_MEM_RUSER_WIDTH - 1:0] m_axi_mem_RUSER;
input  [1:0] m_axi_mem_RRESP;
input   m_axi_mem_BVALID;
output   m_axi_mem_BREADY;
input  [1:0] m_axi_mem_BRESP;
input  [C_M_AXI_MEM_ID_WIDTH - 1:0] m_axi_mem_BID;
input  [C_M_AXI_MEM_BUSER_WIDTH - 1:0] m_axi_mem_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [19:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] A_IN;
wire   [63:0] A_OUT;
reg    mem_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    mem_blk_n_AW;
wire    ap_CS_fsm_state13;
reg    mem_blk_n_B;
wire    ap_CS_fsm_state20;
reg   [58:0] trunc_ln_reg_207;
reg   [58:0] trunc_ln1_reg_213;
reg   [3:0] A_local_address0;
reg    A_local_ce0;
reg    A_local_we0;
wire   [15:0] A_local_q0;
reg    A_local_ce1;
reg    A_local_we1;
reg   [3:0] A_local_1_address0;
reg    A_local_1_ce0;
reg    A_local_1_we0;
wire   [15:0] A_local_1_q0;
reg    A_local_1_ce1;
reg    A_local_1_we1;
reg   [3:0] A_local_2_address0;
reg    A_local_2_ce0;
reg    A_local_2_we0;
wire   [15:0] A_local_2_q0;
reg    A_local_2_ce1;
reg    A_local_2_we1;
reg   [3:0] A_local_3_address0;
reg    A_local_3_ce0;
reg    A_local_3_we0;
wire   [15:0] A_local_3_q0;
reg    A_local_3_ce1;
reg    A_local_3_we1;
reg   [3:0] A_local_4_address0;
reg    A_local_4_ce0;
reg    A_local_4_we0;
wire   [15:0] A_local_4_q0;
reg    A_local_4_ce1;
reg    A_local_4_we1;
reg   [3:0] B_local_address0;
reg    B_local_ce0;
reg    B_local_we0;
wire   [15:0] B_local_q0;
reg    B_local_ce1;
wire   [15:0] B_local_q1;
reg   [3:0] B_local_1_address0;
reg    B_local_1_ce0;
reg    B_local_1_we0;
wire   [15:0] B_local_1_q0;
reg    B_local_1_ce1;
wire   [15:0] B_local_1_q1;
reg   [3:0] B_local_2_address0;
reg    B_local_2_ce0;
reg    B_local_2_we0;
wire   [15:0] B_local_2_q0;
reg    B_local_2_ce1;
wire   [15:0] B_local_2_q1;
reg   [3:0] B_local_3_address0;
reg    B_local_3_ce0;
reg    B_local_3_we0;
wire   [15:0] B_local_3_q0;
reg    B_local_3_ce1;
wire   [15:0] B_local_3_q1;
reg   [3:0] B_local_4_address0;
reg    B_local_4_ce0;
reg    B_local_4_we0;
wire   [15:0] B_local_4_q0;
reg    B_local_4_ce1;
wire   [15:0] B_local_4_q1;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_ap_start;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_ap_done;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_ap_idle;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_ap_ready;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWVALID;
wire   [63:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWADDR;
wire   [0:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWID;
wire   [31:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWLEN;
wire   [2:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWSIZE;
wire   [1:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWBURST;
wire   [1:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWLOCK;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWCACHE;
wire   [2:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWPROT;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWQOS;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWREGION;
wire   [0:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWUSER;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_WVALID;
wire   [255:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_WDATA;
wire   [31:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_WSTRB;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_WLAST;
wire   [0:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_WID;
wire   [0:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_WUSER;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARVALID;
wire   [63:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARADDR;
wire   [0:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARID;
wire   [31:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARLEN;
wire   [2:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARSIZE;
wire   [1:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARBURST;
wire   [1:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARLOCK;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARCACHE;
wire   [2:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARPROT;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARQOS;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARREGION;
wire   [0:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARUSER;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_RREADY;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_BREADY;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_address0;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_ce0;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_we0;
wire   [15:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_d0;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_address1;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_ce1;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_we1;
wire   [15:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_d1;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_address0;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_ce0;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_we0;
wire   [15:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_d0;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_address1;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_ce1;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_we1;
wire   [15:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_d1;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_address0;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_ce0;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_we0;
wire   [15:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_d0;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_address1;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_ce1;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_we1;
wire   [15:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_d1;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_address0;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_ce0;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_we0;
wire   [15:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_d0;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_address1;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_ce1;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_we1;
wire   [15:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_d1;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_address0;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_ce0;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_we0;
wire   [15:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_d0;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_address1;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_ce1;
wire    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_we1;
wire   [15:0] grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_d1;
wire    grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_ap_start;
wire    grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_ap_done;
wire    grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_ap_idle;
wire    grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_ap_ready;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_4_address0;
wire    grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_4_ce0;
wire    grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_4_we0;
wire   [15:0] grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_4_d0;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_3_address0;
wire    grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_3_ce0;
wire    grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_3_we0;
wire   [15:0] grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_3_d0;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_2_address0;
wire    grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_2_ce0;
wire    grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_2_we0;
wire   [15:0] grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_2_d0;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_1_address0;
wire    grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_1_ce0;
wire    grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_1_we0;
wire   [15:0] grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_1_d0;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_address0;
wire    grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_ce0;
wire    grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_we0;
wire   [15:0] grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_d0;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_address0;
wire    grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_ce0;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_1_address0;
wire    grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_1_ce0;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_2_address0;
wire    grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_2_ce0;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_3_address0;
wire    grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_3_ce0;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_4_address0;
wire    grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_4_ce0;
wire    grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_ap_start;
wire    grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_ap_done;
wire    grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_ap_idle;
wire    grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_ap_ready;
wire    grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWVALID;
wire   [63:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWADDR;
wire   [0:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWID;
wire   [31:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWLEN;
wire   [2:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWSIZE;
wire   [1:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWBURST;
wire   [1:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWLOCK;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWCACHE;
wire   [2:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWPROT;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWQOS;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWREGION;
wire   [0:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWUSER;
wire    grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_WVALID;
wire   [255:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_WDATA;
wire   [31:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_WSTRB;
wire    grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_WLAST;
wire   [0:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_WID;
wire   [0:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_WUSER;
wire    grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARVALID;
wire   [63:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARADDR;
wire   [0:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARID;
wire   [31:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARLEN;
wire   [2:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARSIZE;
wire   [1:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARBURST;
wire   [1:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARLOCK;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARCACHE;
wire   [2:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARPROT;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARQOS;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARREGION;
wire   [0:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARUSER;
wire    grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_RREADY;
wire    grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_BREADY;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_address0;
wire    grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_ce0;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_address1;
wire    grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_ce1;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_1_address0;
wire    grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_1_ce0;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_1_address1;
wire    grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_1_ce1;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_2_address0;
wire    grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_2_ce0;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_2_address1;
wire    grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_2_ce1;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_3_address0;
wire    grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_3_ce0;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_3_address1;
wire    grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_3_ce1;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_4_address0;
wire    grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_4_ce0;
wire   [3:0] grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_4_address1;
wire    grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_4_ce1;
reg    mem_AWVALID;
wire    mem_AWREADY;
reg   [63:0] mem_AWADDR;
reg   [31:0] mem_AWLEN;
reg    mem_WVALID;
wire    mem_WREADY;
reg    mem_ARVALID;
wire    mem_ARREADY;
reg   [63:0] mem_ARADDR;
reg   [31:0] mem_ARLEN;
wire    mem_RVALID;
reg    mem_RREADY;
wire   [255:0] mem_RDATA;
wire   [8:0] mem_RFIFONUM;
wire    mem_BVALID;
reg    mem_BREADY;
reg    grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg    grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_ap_start_reg;
wire    ap_CS_fsm_state12;
reg    grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_ap_start_reg;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire  signed [63:0] sext_ln10_fu_187_p1;
wire  signed [63:0] sext_ln30_fu_197_p1;
reg   [19:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 20'd1;
#0 grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_ap_start_reg = 1'b0;
#0 grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_ap_start_reg = 1'b0;
#0 grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_ap_start_reg = 1'b0;
end

main_func_A_local_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
A_local_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_local_address0),
    .ce0(A_local_ce0),
    .we0(A_local_we0),
    .d0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_d0),
    .q0(A_local_q0),
    .address1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_address1),
    .ce1(A_local_ce1),
    .we1(A_local_we1),
    .d1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_d1)
);

main_func_A_local_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
A_local_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_local_1_address0),
    .ce0(A_local_1_ce0),
    .we0(A_local_1_we0),
    .d0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_d0),
    .q0(A_local_1_q0),
    .address1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_address1),
    .ce1(A_local_1_ce1),
    .we1(A_local_1_we1),
    .d1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_d1)
);

main_func_A_local_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
A_local_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_local_2_address0),
    .ce0(A_local_2_ce0),
    .we0(A_local_2_we0),
    .d0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_d0),
    .q0(A_local_2_q0),
    .address1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_address1),
    .ce1(A_local_2_ce1),
    .we1(A_local_2_we1),
    .d1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_d1)
);

main_func_A_local_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
A_local_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_local_3_address0),
    .ce0(A_local_3_ce0),
    .we0(A_local_3_we0),
    .d0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_d0),
    .q0(A_local_3_q0),
    .address1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_address1),
    .ce1(A_local_3_ce1),
    .we1(A_local_3_we1),
    .d1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_d1)
);

main_func_A_local_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
A_local_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_local_4_address0),
    .ce0(A_local_4_ce0),
    .we0(A_local_4_we0),
    .d0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_d0),
    .q0(A_local_4_q0),
    .address1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_address1),
    .ce1(A_local_4_ce1),
    .we1(A_local_4_we1),
    .d1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_d1)
);

main_func_B_local_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
B_local_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_local_address0),
    .ce0(B_local_ce0),
    .we0(B_local_we0),
    .d0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_d0),
    .q0(B_local_q0),
    .address1(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_address1),
    .ce1(B_local_ce1),
    .q1(B_local_q1)
);

main_func_B_local_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
B_local_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_local_1_address0),
    .ce0(B_local_1_ce0),
    .we0(B_local_1_we0),
    .d0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_1_d0),
    .q0(B_local_1_q0),
    .address1(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_1_address1),
    .ce1(B_local_1_ce1),
    .q1(B_local_1_q1)
);

main_func_B_local_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
B_local_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_local_2_address0),
    .ce0(B_local_2_ce0),
    .we0(B_local_2_we0),
    .d0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_2_d0),
    .q0(B_local_2_q0),
    .address1(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_2_address1),
    .ce1(B_local_2_ce1),
    .q1(B_local_2_q1)
);

main_func_B_local_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
B_local_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_local_3_address0),
    .ce0(B_local_3_ce0),
    .we0(B_local_3_we0),
    .d0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_3_d0),
    .q0(B_local_3_q0),
    .address1(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_3_address1),
    .ce1(B_local_3_ce1),
    .q1(B_local_3_q1)
);

main_func_B_local_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
B_local_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_local_4_address0),
    .ce0(B_local_4_ce0),
    .we0(B_local_4_we0),
    .d0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_4_d0),
    .q0(B_local_4_q0),
    .address1(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_4_address1),
    .ce1(B_local_4_ce1),
    .q1(B_local_4_q1)
);

main_func_main_func_Pipeline_VITIS_LOOP_10_1 grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_ap_start),
    .ap_done(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_ap_done),
    .ap_idle(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_ap_idle),
    .ap_ready(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_ap_ready),
    .m_axi_mem_AWVALID(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWVALID),
    .m_axi_mem_AWREADY(1'b0),
    .m_axi_mem_AWADDR(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWADDR),
    .m_axi_mem_AWID(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWID),
    .m_axi_mem_AWLEN(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWLEN),
    .m_axi_mem_AWSIZE(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWSIZE),
    .m_axi_mem_AWBURST(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWBURST),
    .m_axi_mem_AWLOCK(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWLOCK),
    .m_axi_mem_AWCACHE(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWCACHE),
    .m_axi_mem_AWPROT(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWPROT),
    .m_axi_mem_AWQOS(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWQOS),
    .m_axi_mem_AWREGION(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWREGION),
    .m_axi_mem_AWUSER(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_AWUSER),
    .m_axi_mem_WVALID(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_WVALID),
    .m_axi_mem_WREADY(1'b0),
    .m_axi_mem_WDATA(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_WDATA),
    .m_axi_mem_WSTRB(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_WSTRB),
    .m_axi_mem_WLAST(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_WLAST),
    .m_axi_mem_WID(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_WID),
    .m_axi_mem_WUSER(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_WUSER),
    .m_axi_mem_ARVALID(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARVALID),
    .m_axi_mem_ARREADY(mem_ARREADY),
    .m_axi_mem_ARADDR(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARADDR),
    .m_axi_mem_ARID(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARID),
    .m_axi_mem_ARLEN(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARLEN),
    .m_axi_mem_ARSIZE(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARSIZE),
    .m_axi_mem_ARBURST(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARBURST),
    .m_axi_mem_ARLOCK(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARLOCK),
    .m_axi_mem_ARCACHE(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARCACHE),
    .m_axi_mem_ARPROT(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARPROT),
    .m_axi_mem_ARQOS(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARQOS),
    .m_axi_mem_ARREGION(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARREGION),
    .m_axi_mem_ARUSER(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARUSER),
    .m_axi_mem_RVALID(mem_RVALID),
    .m_axi_mem_RREADY(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_RREADY),
    .m_axi_mem_RDATA(mem_RDATA),
    .m_axi_mem_RLAST(1'b0),
    .m_axi_mem_RID(1'd0),
    .m_axi_mem_RFIFONUM(mem_RFIFONUM),
    .m_axi_mem_RUSER(1'd0),
    .m_axi_mem_RRESP(2'd0),
    .m_axi_mem_BVALID(1'b0),
    .m_axi_mem_BREADY(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_BREADY),
    .m_axi_mem_BRESP(2'd0),
    .m_axi_mem_BID(1'd0),
    .m_axi_mem_BUSER(1'd0),
    .sext_ln10(trunc_ln_reg_207),
    .A_local_4_address0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_address0),
    .A_local_4_ce0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_ce0),
    .A_local_4_we0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_we0),
    .A_local_4_d0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_d0),
    .A_local_4_address1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_address1),
    .A_local_4_ce1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_ce1),
    .A_local_4_we1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_we1),
    .A_local_4_d1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_d1),
    .A_local_3_address0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_address0),
    .A_local_3_ce0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_ce0),
    .A_local_3_we0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_we0),
    .A_local_3_d0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_d0),
    .A_local_3_address1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_address1),
    .A_local_3_ce1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_ce1),
    .A_local_3_we1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_we1),
    .A_local_3_d1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_d1),
    .A_local_2_address0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_address0),
    .A_local_2_ce0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_ce0),
    .A_local_2_we0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_we0),
    .A_local_2_d0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_d0),
    .A_local_2_address1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_address1),
    .A_local_2_ce1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_ce1),
    .A_local_2_we1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_we1),
    .A_local_2_d1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_d1),
    .A_local_1_address0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_address0),
    .A_local_1_ce0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_ce0),
    .A_local_1_we0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_we0),
    .A_local_1_d0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_d0),
    .A_local_1_address1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_address1),
    .A_local_1_ce1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_ce1),
    .A_local_1_we1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_we1),
    .A_local_1_d1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_d1),
    .A_local_address0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_address0),
    .A_local_ce0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_ce0),
    .A_local_we0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_we0),
    .A_local_d0(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_d0),
    .A_local_address1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_address1),
    .A_local_ce1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_ce1),
    .A_local_we1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_we1),
    .A_local_d1(grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_d1)
);

main_func_main_func_Pipeline_VITIS_LOOP_22_3 grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_ap_start),
    .ap_done(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_ap_done),
    .ap_idle(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_ap_idle),
    .ap_ready(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_ap_ready),
    .B_local_4_address0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_4_address0),
    .B_local_4_ce0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_4_ce0),
    .B_local_4_we0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_4_we0),
    .B_local_4_d0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_4_d0),
    .B_local_3_address0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_3_address0),
    .B_local_3_ce0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_3_ce0),
    .B_local_3_we0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_3_we0),
    .B_local_3_d0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_3_d0),
    .B_local_2_address0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_2_address0),
    .B_local_2_ce0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_2_ce0),
    .B_local_2_we0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_2_we0),
    .B_local_2_d0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_2_d0),
    .B_local_1_address0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_1_address0),
    .B_local_1_ce0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_1_ce0),
    .B_local_1_we0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_1_we0),
    .B_local_1_d0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_1_d0),
    .B_local_address0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_address0),
    .B_local_ce0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_ce0),
    .B_local_we0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_we0),
    .B_local_d0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_d0),
    .A_local_address0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_address0),
    .A_local_ce0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_ce0),
    .A_local_q0(A_local_q0),
    .A_local_1_address0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_1_address0),
    .A_local_1_ce0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_1_ce0),
    .A_local_1_q0(A_local_1_q0),
    .A_local_2_address0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_2_address0),
    .A_local_2_ce0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_2_ce0),
    .A_local_2_q0(A_local_2_q0),
    .A_local_3_address0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_3_address0),
    .A_local_3_ce0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_3_ce0),
    .A_local_3_q0(A_local_3_q0),
    .A_local_4_address0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_4_address0),
    .A_local_4_ce0(grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_4_ce0),
    .A_local_4_q0(A_local_4_q0)
);

main_func_main_func_Pipeline_VITIS_LOOP_30_4 grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_ap_start),
    .ap_done(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_ap_done),
    .ap_idle(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_ap_idle),
    .ap_ready(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_ap_ready),
    .m_axi_mem_AWVALID(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWVALID),
    .m_axi_mem_AWREADY(mem_AWREADY),
    .m_axi_mem_AWADDR(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWADDR),
    .m_axi_mem_AWID(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWID),
    .m_axi_mem_AWLEN(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWLEN),
    .m_axi_mem_AWSIZE(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWSIZE),
    .m_axi_mem_AWBURST(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWBURST),
    .m_axi_mem_AWLOCK(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWLOCK),
    .m_axi_mem_AWCACHE(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWCACHE),
    .m_axi_mem_AWPROT(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWPROT),
    .m_axi_mem_AWQOS(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWQOS),
    .m_axi_mem_AWREGION(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWREGION),
    .m_axi_mem_AWUSER(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWUSER),
    .m_axi_mem_WVALID(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_WVALID),
    .m_axi_mem_WREADY(mem_WREADY),
    .m_axi_mem_WDATA(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_WDATA),
    .m_axi_mem_WSTRB(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_WSTRB),
    .m_axi_mem_WLAST(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_WLAST),
    .m_axi_mem_WID(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_WID),
    .m_axi_mem_WUSER(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_WUSER),
    .m_axi_mem_ARVALID(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARVALID),
    .m_axi_mem_ARREADY(1'b0),
    .m_axi_mem_ARADDR(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARADDR),
    .m_axi_mem_ARID(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARID),
    .m_axi_mem_ARLEN(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARLEN),
    .m_axi_mem_ARSIZE(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARSIZE),
    .m_axi_mem_ARBURST(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARBURST),
    .m_axi_mem_ARLOCK(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARLOCK),
    .m_axi_mem_ARCACHE(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARCACHE),
    .m_axi_mem_ARPROT(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARPROT),
    .m_axi_mem_ARQOS(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARQOS),
    .m_axi_mem_ARREGION(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARREGION),
    .m_axi_mem_ARUSER(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_ARUSER),
    .m_axi_mem_RVALID(1'b0),
    .m_axi_mem_RREADY(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_RREADY),
    .m_axi_mem_RDATA(256'd0),
    .m_axi_mem_RLAST(1'b0),
    .m_axi_mem_RID(1'd0),
    .m_axi_mem_RFIFONUM(9'd0),
    .m_axi_mem_RUSER(1'd0),
    .m_axi_mem_RRESP(2'd0),
    .m_axi_mem_BVALID(mem_BVALID),
    .m_axi_mem_BREADY(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_BREADY),
    .m_axi_mem_BRESP(2'd0),
    .m_axi_mem_BID(1'd0),
    .m_axi_mem_BUSER(1'd0),
    .sext_ln30(trunc_ln1_reg_213),
    .B_local_address0(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_address0),
    .B_local_ce0(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_ce0),
    .B_local_q0(B_local_q0),
    .B_local_address1(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_address1),
    .B_local_ce1(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_ce1),
    .B_local_q1(B_local_q1),
    .B_local_1_address0(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_1_address0),
    .B_local_1_ce0(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_1_ce0),
    .B_local_1_q0(B_local_1_q0),
    .B_local_1_address1(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_1_address1),
    .B_local_1_ce1(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_1_ce1),
    .B_local_1_q1(B_local_1_q1),
    .B_local_2_address0(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_2_address0),
    .B_local_2_ce0(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_2_ce0),
    .B_local_2_q0(B_local_2_q0),
    .B_local_2_address1(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_2_address1),
    .B_local_2_ce1(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_2_ce1),
    .B_local_2_q1(B_local_2_q1),
    .B_local_3_address0(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_3_address0),
    .B_local_3_ce0(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_3_ce0),
    .B_local_3_q0(B_local_3_q0),
    .B_local_3_address1(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_3_address1),
    .B_local_3_ce1(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_3_ce1),
    .B_local_3_q1(B_local_3_q1),
    .B_local_4_address0(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_4_address0),
    .B_local_4_ce0(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_4_ce0),
    .B_local_4_q0(B_local_4_q0),
    .B_local_4_address1(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_4_address1),
    .B_local_4_ce1(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_4_ce1),
    .B_local_4_q1(B_local_4_q1)
);

main_func_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .A_IN(A_IN),
    .A_OUT(A_OUT)
);

main_func_mem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_MEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_MEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_MEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_MEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_MEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_MEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_MEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_MEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_MEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_MEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_MEM_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 256 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
mem_m_axi_U(
    .AWVALID(m_axi_mem_AWVALID),
    .AWREADY(m_axi_mem_AWREADY),
    .AWADDR(m_axi_mem_AWADDR),
    .AWID(m_axi_mem_AWID),
    .AWLEN(m_axi_mem_AWLEN),
    .AWSIZE(m_axi_mem_AWSIZE),
    .AWBURST(m_axi_mem_AWBURST),
    .AWLOCK(m_axi_mem_AWLOCK),
    .AWCACHE(m_axi_mem_AWCACHE),
    .AWPROT(m_axi_mem_AWPROT),
    .AWQOS(m_axi_mem_AWQOS),
    .AWREGION(m_axi_mem_AWREGION),
    .AWUSER(m_axi_mem_AWUSER),
    .WVALID(m_axi_mem_WVALID),
    .WREADY(m_axi_mem_WREADY),
    .WDATA(m_axi_mem_WDATA),
    .WSTRB(m_axi_mem_WSTRB),
    .WLAST(m_axi_mem_WLAST),
    .WID(m_axi_mem_WID),
    .WUSER(m_axi_mem_WUSER),
    .ARVALID(m_axi_mem_ARVALID),
    .ARREADY(m_axi_mem_ARREADY),
    .ARADDR(m_axi_mem_ARADDR),
    .ARID(m_axi_mem_ARID),
    .ARLEN(m_axi_mem_ARLEN),
    .ARSIZE(m_axi_mem_ARSIZE),
    .ARBURST(m_axi_mem_ARBURST),
    .ARLOCK(m_axi_mem_ARLOCK),
    .ARCACHE(m_axi_mem_ARCACHE),
    .ARPROT(m_axi_mem_ARPROT),
    .ARQOS(m_axi_mem_ARQOS),
    .ARREGION(m_axi_mem_ARREGION),
    .ARUSER(m_axi_mem_ARUSER),
    .RVALID(m_axi_mem_RVALID),
    .RREADY(m_axi_mem_RREADY),
    .RDATA(m_axi_mem_RDATA),
    .RLAST(m_axi_mem_RLAST),
    .RID(m_axi_mem_RID),
    .RUSER(m_axi_mem_RUSER),
    .RRESP(m_axi_mem_RRESP),
    .BVALID(m_axi_mem_BVALID),
    .BREADY(m_axi_mem_BREADY),
    .BRESP(m_axi_mem_BRESP),
    .BID(m_axi_mem_BID),
    .BUSER(m_axi_mem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(mem_ARVALID),
    .I_ARREADY(mem_ARREADY),
    .I_ARADDR(mem_ARADDR),
    .I_ARLEN(mem_ARLEN),
    .I_RVALID(mem_RVALID),
    .I_RREADY(mem_RREADY),
    .I_RDATA(mem_RDATA),
    .I_RFIFONUM(mem_RFIFONUM),
    .I_AWVALID(mem_AWVALID),
    .I_AWREADY(mem_AWREADY),
    .I_AWADDR(mem_AWADDR),
    .I_AWLEN(mem_AWLEN),
    .I_WVALID(mem_WVALID),
    .I_WREADY(mem_WREADY),
    .I_WDATA(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_WDATA),
    .I_WSTRB(grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_WSTRB),
    .I_BVALID(mem_BVALID),
    .I_BREADY(mem_BREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_ap_start_reg <= 1'b1;
        end else if ((grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_ap_ready == 1'b1)) begin
            grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_ap_start_reg <= 1'b1;
        end else if ((grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_ap_ready == 1'b1)) begin
            grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_ap_start_reg <= 1'b1;
        end else if ((grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_ap_ready == 1'b1)) begin
            grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln1_reg_213 <= {{A_OUT[63:5]}};
        trunc_ln_reg_207 <= {{A_IN[63:5]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        A_local_1_address0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_1_address0 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_address0;
    end else begin
        A_local_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        A_local_1_ce0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_1_ce0 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_ce0;
    end else begin
        A_local_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_1_ce1 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_ce1;
    end else begin
        A_local_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_1_we0 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_we0;
    end else begin
        A_local_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_1_we1 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_1_we1;
    end else begin
        A_local_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        A_local_2_address0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_2_address0 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_address0;
    end else begin
        A_local_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        A_local_2_ce0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_2_ce0 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_ce0;
    end else begin
        A_local_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_2_ce1 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_ce1;
    end else begin
        A_local_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_2_we0 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_we0;
    end else begin
        A_local_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_2_we1 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_2_we1;
    end else begin
        A_local_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        A_local_3_address0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_3_address0 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_address0;
    end else begin
        A_local_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        A_local_3_ce0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_3_ce0 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_ce0;
    end else begin
        A_local_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_3_ce1 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_ce1;
    end else begin
        A_local_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_3_we0 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_we0;
    end else begin
        A_local_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_3_we1 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_3_we1;
    end else begin
        A_local_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        A_local_4_address0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_4_address0 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_address0;
    end else begin
        A_local_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        A_local_4_ce0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_4_ce0 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_ce0;
    end else begin
        A_local_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_4_ce1 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_ce1;
    end else begin
        A_local_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_4_we0 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_we0;
    end else begin
        A_local_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_4_we1 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_4_we1;
    end else begin
        A_local_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        A_local_address0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_address0 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_address0;
    end else begin
        A_local_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        A_local_ce0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_A_local_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_ce0 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_ce0;
    end else begin
        A_local_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_ce1 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_ce1;
    end else begin
        A_local_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_we0 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_we0;
    end else begin
        A_local_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_local_we1 = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_A_local_we1;
    end else begin
        A_local_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        B_local_1_address0 = grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        B_local_1_address0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_1_address0;
    end else begin
        B_local_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        B_local_1_ce0 = grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        B_local_1_ce0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_1_ce0;
    end else begin
        B_local_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        B_local_1_ce1 = grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_1_ce1;
    end else begin
        B_local_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        B_local_1_we0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_1_we0;
    end else begin
        B_local_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        B_local_2_address0 = grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        B_local_2_address0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_2_address0;
    end else begin
        B_local_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        B_local_2_ce0 = grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        B_local_2_ce0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_2_ce0;
    end else begin
        B_local_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        B_local_2_ce1 = grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_2_ce1;
    end else begin
        B_local_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        B_local_2_we0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_2_we0;
    end else begin
        B_local_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        B_local_3_address0 = grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        B_local_3_address0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_3_address0;
    end else begin
        B_local_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        B_local_3_ce0 = grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        B_local_3_ce0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_3_ce0;
    end else begin
        B_local_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        B_local_3_ce1 = grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_3_ce1;
    end else begin
        B_local_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        B_local_3_we0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_3_we0;
    end else begin
        B_local_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        B_local_4_address0 = grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        B_local_4_address0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_4_address0;
    end else begin
        B_local_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        B_local_4_ce0 = grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        B_local_4_ce0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_4_ce0;
    end else begin
        B_local_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        B_local_4_ce1 = grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_4_ce1;
    end else begin
        B_local_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        B_local_4_we0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_4_we0;
    end else begin
        B_local_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        B_local_address0 = grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        B_local_address0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_address0;
    end else begin
        B_local_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        B_local_ce0 = grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        B_local_ce0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_ce0;
    end else begin
        B_local_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        B_local_ce1 = grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_B_local_ce1;
    end else begin
        B_local_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        B_local_we0 = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_B_local_we0;
    end else begin
        B_local_we0 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if (((mem_AWREADY == 1'b0) | (grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_ap_done == 1'b0))) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((mem_BVALID == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

always @ (*) begin
    if ((mem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((mem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((mem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((mem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        mem_ARADDR = sext_ln10_fu_187_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        mem_ARADDR = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARADDR;
    end else begin
        mem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((mem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        mem_ARLEN = 32'd5;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        mem_ARLEN = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARLEN;
    end else begin
        mem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((mem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        mem_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        mem_ARVALID = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_ARVALID;
    end else begin
        mem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((mem_AWREADY == 1'b0) | (grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state13))) begin
        mem_AWADDR = sext_ln30_fu_197_p1;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        mem_AWADDR = grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWADDR;
    end else begin
        mem_AWADDR = 'bx;
    end
end

always @ (*) begin
    if ((~((mem_AWREADY == 1'b0) | (grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state13))) begin
        mem_AWLEN = 32'd5;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        mem_AWLEN = grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWLEN;
    end else begin
        mem_AWLEN = 'bx;
    end
end

always @ (*) begin
    if ((~((mem_AWREADY == 1'b0) | (grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state13))) begin
        mem_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        mem_AWVALID = grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_AWVALID;
    end else begin
        mem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((mem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
        mem_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        mem_BREADY = grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_BREADY;
    end else begin
        mem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        mem_RREADY = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_m_axi_mem_RREADY;
    end else begin
        mem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        mem_WVALID = grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_m_axi_mem_WVALID;
    end else begin
        mem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mem_blk_n_AR = m_axi_mem_ARREADY;
    end else begin
        mem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        mem_blk_n_AW = m_axi_mem_AWREADY;
    end else begin
        mem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        mem_blk_n_B = m_axi_mem_BVALID;
    end else begin
        mem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((mem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if ((~((mem_AWREADY == 1'b0) | (grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((mem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_ap_start = grp_main_func_Pipeline_VITIS_LOOP_10_1_fu_129_ap_start_reg;

assign grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_ap_start = grp_main_func_Pipeline_VITIS_LOOP_22_3_fu_141_ap_start_reg;

assign grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_ap_start = grp_main_func_Pipeline_VITIS_LOOP_30_4_fu_155_ap_start_reg;

assign sext_ln10_fu_187_p1 = $signed(trunc_ln_reg_207);

assign sext_ln30_fu_197_p1 = $signed(trunc_ln1_reg_213);

endmodule //main_func
